### ISSUE TITLE
Can't find it in operator search

### ISSUE THREAD

**Issue by noobtoob4lyfe** [lukas-toenne/voronoi_tools#7]
The addon installed without error but I cannot find where to run it.  I searched for "add" and "voronoi" but nothing comes up.  Any ideas?

**Comment by lukas-toenne** [comment]
Sorry, all i can say is "works for me". Nothing in the console either? (_Window > Toggle System Console_ on windows)
![image](https://github.com/lukas-toenne/voronoi_tools/assets/56959571/6f9bc3aa-420f-4763-b2e3-328c2ef27946)

Note that the addon is quite old and not actively maintained.

**Comment by noobtoob4lyfe** [comment]
Thanks for the quick reply.  What version of blender is that?  I'm on 3.5.  

Could I possibly just run the individual python scripts manually in the scripting tab or does that not work without your UI?  Is there anything special about how you installed it?  I just used the addon manager in the prefs and installed the zip file with the button.

**Comment by noobtoob4lyfe** [comment]
Looks like it does work in Blender v2.82.9!   However I'm getting this error when running the operator.  I've selected my point cloud, then shift selected my cube object and then I run the addon.  

"Error: Traceback (most recent call last):
  File "C:\Users\importon\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\voronoi_tools-master\operator.py", line 151, in execute
    bm = self.generate_bmesh(triangulator, points)
  File "C:\Users\importon\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\voronoi_tools-master\operator.py", line 125, in generate_bmesh
    return triangulator.construct_delaunay(points)
  File "C:\Users\importon\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\voronoi_tools-master\triangulator.py", line 480, in construct_delaunay
    self._create_triangulation(points)
  File "C:\Users\importon\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\voronoi_tools-master\triangulator.py", line 444, in _create_triangulation
    self._do_edgeflip()
  File "C:\Users\importon\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\voronoi_tools-master\triangulator.py", line 397, in _do_edgeflip
    bm.faces.new((verts[2], verts[3], verts[1]))
ValueError: faces.new(verts): face already exists

location: <unknown location>:-1"

**Comment by lukas-toenne** [comment]
I've tested different Blender versions and i can confirm it does not work in 3.5.1 for some reason, but it does work in 3.6.1 and 4.0 (latest). Is using 3.6 an option for you?

**Comment by noobtoob4lyfe** [comment]
Thanks again for your help!  
Yes 3.6 is no problem for me.  However I think may not be understanding how to use the tool?  Here's what I've been doing which results in an error.  

1. Selecting my point cloud 
2. Ctrl selecting my plane object
3. Clicking on "Add Voronoi Cells" in the operator
4. Error

Are those the correct steps?  

![image](https://github.com/lukas-toenne/voronoi_tools/assets/43832374/76c7071a-217f-4a89-8e00-56354cb07fab)

**Comment by noobtoob4lyfe** [comment]
Just a quick update.  I tried version 2.9, 3.0, and 3.6.1 as well, and once again the operator cannot be found in the search menu.  I really would love to get this working on my end,  would it be too much to ask if you could share some screen captures of the correct workflow?  I'm thinking it could be a simple misunderstanding on my part that is preventing me from success.

**Comment by user-vm** [comment]
> Okay, I've figured out how to get things working. Thanks for your help.

How did you manage this? I am getting the same error. It either complains about the face already existing in the target mesh if I check "Use Mesh Sources", and if I don't check it, the target mesh just vanishes.
